[project]
name = "bitcoin-descriptor-specification"
version = "0.1.0"
description = "Bitcoin Descriptor Specification"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arpeggio>=2.0.3",
]
